/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 *  Sunlly0 2022.8.18
 *  编译 thrift 文件后自动生成，定义了传输对象结构体
 *  JsonString: 以字符串形式传输 upstreamResult
 *
 */
package org.team3090.simple.Worker.rpcClass;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-08-17")
public class JsonString implements org.apache.thrift.TBase<JsonString, JsonString._Fields>, java.io.Serializable, Cloneable, Comparable<JsonString> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JsonString");

  private static final org.apache.thrift.protocol.TField UPSTREAM_RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("upstreamResult", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new JsonStringStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new JsonStringTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable String upstreamResult; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UPSTREAM_RESULT((short)1, "upstreamResult");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UPSTREAM_RESULT
          return UPSTREAM_RESULT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.UPSTREAM_RESULT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UPSTREAM_RESULT, new org.apache.thrift.meta_data.FieldMetaData("upstreamResult", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "String")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JsonString.class, metaDataMap);
  }

  public JsonString() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JsonString(JsonString other) {
    if (other.isSetUpstreamResult()) {
      this.upstreamResult = other.upstreamResult;
    }
  }

  public JsonString deepCopy() {
    return new JsonString(this);
  }

  @Override
  public void clear() {
    this.upstreamResult = null;
  }

  @org.apache.thrift.annotation.Nullable
  public String getUpstreamResult() {
    return this.upstreamResult;
  }

  public JsonString setUpstreamResult(@org.apache.thrift.annotation.Nullable String upstreamResult) {
    this.upstreamResult = upstreamResult;
    return this;
  }

  public void unsetUpstreamResult() {
    this.upstreamResult = null;
  }

  /** Returns true if field upstreamResult is set (has been assigned a value) and false otherwise */
  public boolean isSetUpstreamResult() {
    return this.upstreamResult != null;
  }

  public void setUpstreamResultIsSet(boolean value) {
    if (!value) {
      this.upstreamResult = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case UPSTREAM_RESULT:
      if (value == null) {
        unsetUpstreamResult();
      } else {
        setUpstreamResult((String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UPSTREAM_RESULT:
      return getUpstreamResult();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case UPSTREAM_RESULT:
      return isSetUpstreamResult();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof JsonString)
      return this.equals((JsonString)that);
    return false;
  }

  public boolean equals(JsonString that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_upstreamResult = true && this.isSetUpstreamResult();
    boolean that_present_upstreamResult = true && that.isSetUpstreamResult();
    if (this_present_upstreamResult || that_present_upstreamResult) {
      if (!(this_present_upstreamResult && that_present_upstreamResult))
        return false;
      if (!this.upstreamResult.equals(that.upstreamResult))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetUpstreamResult()) ? 131071 : 524287);
    if (isSetUpstreamResult())
      hashCode = hashCode * 8191 + upstreamResult.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(JsonString other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetUpstreamResult(), other.isSetUpstreamResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpstreamResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.upstreamResult, other.upstreamResult);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("JsonString(");
    boolean first = true;

    if (isSetUpstreamResult()) {
      sb.append("upstreamResult:");
      if (this.upstreamResult == null) {
        sb.append("null");
      } else {
        sb.append(this.upstreamResult);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JsonStringStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JsonStringStandardScheme getScheme() {
      return new JsonStringStandardScheme();
    }
  }

  private static class JsonStringStandardScheme extends org.apache.thrift.scheme.StandardScheme<JsonString> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JsonString struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // UPSTREAM_RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.upstreamResult = iprot.readString();
              struct.setUpstreamResultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JsonString struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.upstreamResult != null) {
        if (struct.isSetUpstreamResult()) {
          oprot.writeFieldBegin(UPSTREAM_RESULT_FIELD_DESC);
          oprot.writeString(struct.upstreamResult);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JsonStringTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JsonStringTupleScheme getScheme() {
      return new JsonStringTupleScheme();
    }
  }

  private static class JsonStringTupleScheme extends org.apache.thrift.scheme.TupleScheme<JsonString> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JsonString struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUpstreamResult()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetUpstreamResult()) {
        oprot.writeString(struct.upstreamResult);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JsonString struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.upstreamResult = iprot.readString();
        struct.setUpstreamResultIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

